apiVersion: v1
kind: Service
metadata:
  name: checkout-svc
  namespace: demo
  labels:
    app: checkout-svc
    managed-by: gitops
spec:
  type: ClusterIP
  selector:
    app: checkout-svc
  ports:
    - name: http
      port: 80
      targetPort: http
